name: mas-marketing
favicon: null
layout_spectrum: 0.5269415634684265
typography_spectrum: 0.665471357293427
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5025078405160457
  lightness: 0.30209582415409386
  saturation: 0.8841699971817434
  rhythmicContrast: 0.40269132843241096
purpose: []
